flags:
  proto-lens-protoc:
    only-executable: true
extra-package-dbs: []
packages:
- '.'
extra-deps:
- haskell-src-exts-1.17.1
- proto-lens-0.1.0.5
- proto-lens-descriptors-0.1.0.5
- proto-lens-protoc-0.1.0.5
explicit-setup-deps:
  proto: true
resolver: lts-8.2
