[package]
name = "ap"
version = "0.1.0"
authors = [ "Sauyon Lee <s@uyon.co>", "Samuel Hindmarch <samuel.hindmarch@keble.ox.ac.uk" ]
build = "build.rs"

[dependencies]
rand = "0.3"
hyper = "0.10.9"
protobuf = "1.2"
ring = "0.7.5"
