[package]
name = "ap"
version = "0.1.0"
authors = [ "Sauyon Lee <s@uyon.co>", "Samuel Hindmarch <samuel.hindmarch@stcatz.ox.ac.uk" ]
#build = "build.rs"

[dependencies]
rand = "0.3"
tiny_http = "0.5"
protobuf = "1.2"
